init python:
    melee_weapons = [
        {"Club":{"type":"simple", "hands": 1, "cost":.1, "damage":(1, 4), "damage_type":"bludgeoning", "weight":2}},
        {"Dagger":{"type":"simple", "hands": 1, "cost":2, "damage":(1, 4), "damage_type":"piercing", "weight":1}},
        {"Greatclub":{"type":"simple", "hands": 2, "cost":.2, "damage":(1, 8), "damage_type":"bludgeoning", "weight":10}},
        {"Handaxe":{"type":"simple", "hands": 1, "cost":5, "damage":(1, 6), "damage_type":"slashing", "weight":2}},
        {"Javelin":{"type":"simple", "hands": 1, "cost":.5, "damage":(1, 6), "damage_type":"piercing", "weight":2}},
        {"Light Hammer":{"type":"simple", "hands": 1, "cost":2, "damage":(1, 4), "damage_type":"bludgeoning", "weight":2}},
        {"Mace":{"type":"simple", "hands": 1, "cost":5, "damage":(1, 6), "damage_type":"bludgeoning", "weight":4}},
        {"Quarterstaff":{"type":"simple", "hands": 1, "cost":.2, "damage":(1, 6), "damage_type":"bludgeoning", "weight":4}},
        {"Sickle":{"type":"simple", "hands": 1, "cost":1, "damage":(1, 4), "damage_type":"slashing", "weight":2}},
        {"Spear":{"type":"simple", "hands": 1, "cost":1, "damage":(1, 6), "damage_type":"piercing", "weight":3}},
        {"Battleaxe":{"type":"martial", "hands": 1, "cost":10, "damage":(1, 8), "damage_type":"slashing", "weight":4}},
        {"Flail":{"type":"martial", "hands": 1, "cost":10, "damage":(1, 8), "damage_type":"bludgeoning", "weight":2}},
        {"Glaive":{"type":"martial", "hands": 2, "cost":20, "damage":(1, 10), "damage_type":"slashing", "weight":6}},
        {"Greataxe":{"type":"martial", "hands": 2, "cost":30, "damage":(1, 12), "damage_type":"slashing", "weight":7}},
        {"Greatsword":{"type":"martial", "hands": 2, "cost":50, "damage":(2, 6), "damage_type":"slashing", "weight":6}},
        {"Halberd":{"type":"martial", "hands": 2, "cost":20, "damage":(1, 10), "damage_type":"slashing", "weight":6}},
        {"Lance":{"type":"martial", "hands": 1, "cost":10, "damage":(1, 12), "damage_type":"piercing", "weight":6}},
        {"Longsword":{"type":"martial", "hands": 1, "cost":15, "damage":(1, 8), "damage_type":"slashing", "weight":3}},
        {"Maul":{"type":"martial", "hands": 2, "cost":10, "damage":(2, 6), "damage_type":"bludgeoning", "weight":10}},
        {"Morningstar":{"type":"martial", "hands": 1, "cost":15, "damage":(1, 8), "damage_type":"piercing", "weight":4}},
        {"Pike":{"type":"martial", "hands": 1, "cost":5, "damage":(1, 10), "damage_type":"piercing", "weight":18}},
        {"Rapier":{"type":"martial", "hands": 1, "cost":25, "damage":(1, 8), "damage_type":"piercing", "weight":2}},
        {"Scimitar":{"type":"martial", "hands": 1, "cost":25, "damage":(1, 6), "damage_type":"slashing", "weight":3}},
        {"Shortsword":{"type":"martial", "hands": 1, "cost":10, "damage":(1, 6), "damage_type":"piercing", "weight":2}},
        {"Trident":{"type":"martial", "hands": 1, "cost":5, "damage":(1, 6), "damage_type":"piercing", "weight":4}},
        {"War Pick":{"type":"martial", "hands": 1, "cost":5, "damage":(1, 8), "damage_type":"piercing", "weight":2}},
        {"Warhammer":{"type":"martial", "hands": 1, "cost":15, "damage":(1, 8), "damage_type":"bludgeoning", "weight":2}},
        {"Whip":{"type":"martial", "hands": 1, "cost":2, "damage":(1, 4), "damage_type":"slashing", "weight":3}},
    ]
    ranged_weapons = [
        {"Light Crossbow":{"type":"simple", "hands": 2, "cost":25, "damage":(1, 8), "damage_type":"piercing", "weight":5}},
        {"Dart":{"type":"simple", "hands": 1, "cost":.05, "damage":(1, 4), "damage_type":"piercing", "weight":0.25}},
        {"Shortbow":{"type":"simple", "hands": 2, "cost":25, "damage":(1, 6), "damage_type":"piercing", "weight":2}},
        {"Sling":{"type":"simple", "hands": 1, "cost":.1, "damage":(1, 4), "damage_type":"bludgeoning", "weight":0}},
        {"Blowgun":{"type":"martial", "hands": 1, "cost":10, "damage":(1, 1), "damage_type":"piercing", "weight":1}},
        {"Hand Crossbow":{"type":"martial", "hands": 1, "cost":75, "damage":(1, 6), "damage_type":"piercing", "weight":3}},
        {"Heavy Crossbow":{"type":"martial", "hands": 1, "cost":50, "damage":(1, 10), "damage_type":"piercing", "weight":18}},
        {"Longbow":{"type":"martial", "hands": 1, "cost":50, "damage":(1, 8), "damage_type":"piercing", "weight":2}},
        {"Net":{"type":"martial", "hands": 1, "cost":1, "damage": "None", "weight":3}}
    ]
    armor = [
        {"Padded":{"cost":5, "armor_class":11 + 3, "weight":8}},
        {"Leather":{"cost":10, "armor_class":11 + 3, "weight":10}},
        {"Studded Leather":{"cost":45, "armor_class":12 + 3, "weight":13}},
        {"Hide":{"cost":10, "armor_class":12 + 2, "weight":12}},
        {"Chain Shirt":{"cost":50, "armor_class":13 + 2, "weight":20}},
        {"Scale Mail":{"cost":50, "armor_class":14 + 2, "weight":45}},
        {"Breastplate":{"cost":400, "armor_class":14 + 2, "weight":20}},
        {"Half Plate":{"cost":750, "armor_class":15 + 2, "weight":40}},
        {"Ring Mail":{"cost":30, "armor_class":14, "weight":40}},
        {"Chain Mail":{"cost":75, "armor_class":16, "weight":55}},
        {"Splint":{"cost":200, "armor_class":17, "weight":60}},
        {"Plate":{"cost":1500, "armor_class":18, "weight":65}},
        {"Shield":{"cost":10, "armor_class":2, "weight":6}}
    ]